### ISSUE TITLE
Trello expects fields as url parameters and not as body (JSON) attributes

### ISSUE THREAD

**Issue by joaodiogocosta** [jeremytregunna/ruby-trello#102]
I encountered this issue while trying to create a webhook using the following code:

```
options = { id_model: "a_valid_id_model", callback_url: "a_valid_callback_url" }

trello = Trello::Client.new(consumer_key: "a_valid_key", consumer_secret: "a_valid_secret", oauth_token: "a_valid_token", oauth_token_secret: "a_valid_secret")

trello.create(:webhook, options)
```

And I get this `[400 POST https://api.trello.com/1/webhooks]: invalid value for idModel` everytime.

I found that Trello excepts those options as URL parameters and not as body (JSON) attributes, and I actually made it work writing the path by hand:

```
trello.post("/webhooks/?idModel=a_valid_id_model&callbackURL=a_valid_callback_url")
```

Any thoughts about this? Thanks

**Comment by xjeline5** [comment]
Me and @Venousek have looked into this issue as part of our school project and we can confirm that this behaviour is still present (under both Ruby 1.9.3 and 2.1.2).

We believe that problem regarding URL has been solved on Trello API side, because when code is run correctly (see below), the webhook is created ok using POST with atrributes sent in request body. We cannot confirm this as API source is not public, but documentation says attributes should be in the body.

The persisting problem is usage of create(path, options) method in Trello::Client class. This method is calling save method of class that is passed as path parameter with options from second param. However, when creating webhook using

    Trello::Webhook.create(options)

method, parameters are first transformed, i.e.:

    attributes[:id_model]        = fields['idModel']

and after that, client.create method is called. This does not happen when calling client.create method directly and causes that attributes of Webhook are not set, therefore resulting in an error.


Here are code examples, that are actually working ok. One drawback in calling it the first way, you have to know the actual names of the attributes, that are different from the names of options.

    options = { 'idModel' => "a_valid_id_model", 'callbackURL' => "a_valid_callback_url" }

    trello = Trello::Client.new(consumer_key: "a_valid_key", consumer_secret: "a_valid_secret", oauth_token: "a_valid_token", oauth_token_secret: "a_valid_secret")

    trello.create(:webhook, options)

or

    options = { id_model: "a_valid_id_model", callback_url: "a_valid_callback_url" }

    trello = Trello::Client.new(consumer_key: "a_valid_key", consumer_secret: "a_valid_secret", oauth_token: "a_valid_token", oauth_token_secret: "a_valid_secret")

    Trello::Webhook.create(options)

If you see any solution of how to make the options for these two calls unified, let us know and we'll try to make a fix.

**Comment by exAspArk** [comment]
I think this issue can be closed? I was able to create a webhook with the latest gem version by using:

```rb
Trello::Webhook.create(model_id: ..., callback_url: ..., description: ..., active: ...)
```

Note that `id_model` was renamed to `model_id` in this commit https://github.com/jeremytregunna/ruby-trello/commit/919028c614e11da20fda37f560ba24975605c87c starting with v3.0.0

**Comment by hoppergee** [comment]
@exAspArk You're right. This issue does not exist any more.
