### ISSUE TITLE
Unable to obtain public key

### ISSUE THREAD

**Issue by rmangino** [jeremytregunna/ruby-trello#167]
I am unable to obtain my public key using the directions listed in the README.md.

```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
 ~/dev
$ gem install ruby-trello
Fetching: ruby-trello-1.3.0.gem (100%)
Successfully installed ruby-trello-1.3.0
1 gem installed
 ~/dev
$ irb -rubygems
2.2.1 :001 > require 'trello'
true
2.2.1 :002 > Trello.open_public_key_url
NoMethodError: undefined method `open_public_key_url' for Trello:Module
	from (irb):2
	from /Users/xxxx/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by rossta** [comment]
@rmangino Sorry you're having trouble. The setup code in the README hasn't been published in a release yet. I'd expect there to be a `1.4` release soon which will include that method.

You can try installing from edge, either by cloning the repo or using `github: 'jeremytredgunna/ruby-trello` option in your `Gemfile` if you're using one. 

Otherwise, here are the non-automated steps:

1. Visit: https://trello.com/app-key 
2. Copy your "key" and "secret"
3. Visit https://trello.com/1/authorize?expiration=never&scope=read,write,account&response_type=token&name=YOUR_APP_NAME&key=YOUR_KEY to grab your member token for "YOUR_APP_NAME"

**Comment by rmangino** [comment]
Awesome - thank you @rossta!
