### ISSUE TITLE
How to get "Email for this card"?

### ISSUE THREAD

**Issue by digitalronin** [jeremytregunna/ruby-trello#244]
I'm trying to return the email address for a card I create via the API. i.e. via the web interface, when you open a card and click the "Share and more" link, there's an "Email for this card." If I send an email to that address, it shows up as a comment from me on the card.

Is there a way to find out this email address via the gem?

**Comment by cheeley** [comment]
Same here. This option would be a huge help in our workflow.

**Comment by codyolsen** [comment]
I looked into it. 
This was the dead end: 
https://stackoverflow.com/a/42517910/2600823

Unfortunately, it looks like Trello doesn't expose the email (always returns nil), even though [it's clearly a documented property in their API docs.](https://developers.trello.com/v1.0/reference#cardsid)

**Comment by cheeley** [comment]
@codyolsen Great info, thank you. I'll look forward to an update from you!

**Comment by codyolsen** [comment]
Closing this for now. It's more on the trello-api side of things. Doesn't seem like having that email for a card come through the api is an option for the time being. Using the api rather than the email address is the current preferred method based on the [security concerns addressed in their response.](https://stackoverflow.com/a/42517910/2600823) I can see the use case for having that email accessible, but it would take more voices to bring that discussion to the top of their queue.
