### ISSUE TITLE
Not possible to create card with label

### ISSUE THREAD

**Issue by daverees4** [jeremytregunna/ruby-trello#303]
Thanks for the great library!  Everything is working fine, except I ran into trouble creating a card with a label.  

For example this doesn't work for me - the card with the title is created but no label added:  

```
label=Trello::Label.find("labelid")
list=Trello::List.find("listid")
card=Trello::Card.new(list_id: list.id, name: "Testcard", labels: [label]).save
```

I can get the label to add after the card has been created: 

`card.add_label(label).save`

**Comment by hoppergee** [comment]
The `labels` attribute is [a read-only attribute](https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/card.rb#L53) due to Trello API.

You can use [`card_labels`](https://github.com/jeremytregunna/ruby-trello/blob/master/lib/trello/card.rb#L65) which needs to assign label IDs on it.

**Comment by daverees4** [comment]
Ah, my mistake sorry.

Can confirm working fine with card_labels.
